### ISSUE TITLE
Automate NPM Publish event

### ISSUE THREAD

**Issue by TriPSs** [TriPSs/react-esc#9]
# Todo
- [ ] Master as protected branch
- [ ] Run some tests with Travis-CI (Do this with the react-esc-example repo?)
- [ ] When merging to master deploy to npm
